development:
  adapter: postgresql
  encoding: utf8
  database: fractalmedia_development
  pool: 5
  username: postgres
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: fractalmedia_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: fractalmedia_development
  pool: 5
  username: root
  password:
